name: server_example
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  buffer: ^1.1.0
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
  http: ^0.13.1
  mustache: ^1.1.1
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.5
